"""Changed structure

Revision ID: 234b65136de9
Revises: 9b721a2ac24c
Create Date: 2025-10-18 17:28:46.051091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '234b65136de9'
down_revision = '9b721a2ac24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_comment_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.comment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'comment_id')
    )
    with op.batch_alter_table('admin_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('decision',
               existing_type=postgresql.ENUM('APPROVED', 'REJECTED', name='reviewstatus'),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reason')

    with op.batch_alter_table('campaign_updates', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_constraint('campaign_updates_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('title')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('goal_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('raised_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='campaignstatus'),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('end_date')
        batch_op.drop_column('long_description')
        batch_op.drop_column('short_description')
        batch_op.drop_column('image_url')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.drop_column('likes_count')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDING', 'SUCCESSFUL', 'FAILED', 'REFUNDED', name='campaignpaymentstatus'),
               type_=sa.Enum('PENDING', 'COMPLETED', 'REFUNDED', 'CANCELLED', name='donationstatus'),
               nullable=True)
        batch_op.drop_constraint('donations_donor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('donor_id')
        batch_op.drop_column('donation_date')
        batch_op.drop_column('message')

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('followed_at')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=postgresql.ENUM('JAZZCASH', 'EASYPAISA', 'DEBIT', 'CREDIT', name='paymentmethod'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_constraint('payments_transaction_ref_key', type_='unique')
        batch_op.drop_column('transaction_ref')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_ref', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('payments_transaction_ref_key', ['transaction_ref'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('payment_method',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('JAZZCASH', 'EASYPAISA', 'DEBIT', 'CREDIT', name='paymentmethod'),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('donation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('donor_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('donations_donor_id_fkey', 'users', ['donor_id'], ['user_id'])
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'COMPLETED', 'REFUNDED', 'CANCELLED', name='donationstatus'),
               type_=postgresql.ENUM('PENDING', 'SUCCESSFUL', 'FAILED', 'REFUNDED', name='campaignpaymentstatus'),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('likes')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=2083), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('short_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('long_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='campaignstatus'),
               nullable=False)
        batch_op.alter_column('raised_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('goal_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('image')
        batch_op.drop_column('description')

    with op.batch_alter_table('campaign_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('campaign_updates_user_id_fkey', 'users', ['user_id'], ['user_id'])
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('admin_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('decision',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('APPROVED', 'REJECTED', name='reviewstatus'),
               nullable=True)
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('comments')

    op.drop_table('user_comment_likes')
    # ### end Alembic commands ###
