"""empty message

Revision ID: 9b721a2ac24c
Revises: 
Create Date: 2025-10-10 19:10:43.526610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b721a2ac24c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('updates')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='campaignstatus'), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('goal_amount',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('raised_amount',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'SUCCESSFUL', 'FAILED', 'REFUNDED', name='campaignpaymentstatus'), nullable=False))
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('transaction_ref', sa.String(length=100), nullable=True))
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('JAZZCASH', 'EASYPAISA', 'DEBIT', 'CREDIT', name='paymentmethod'),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['transaction_ref'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.Enum('DONOR', 'CREATOR', 'ADMIN', name='userrole'), nullable=False))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.drop_column('profile_image')
        batch_op.drop_column('role')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('username')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('payment_method',
               existing_type=sa.Enum('JAZZCASH', 'EASYPAISA', 'DEBIT', 'CREDIT', name='paymentmethod'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('transaction_ref')
        batch_op.drop_column('amount')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('message')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('raised_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=False)
        batch_op.alter_column('goal_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')

    op.create_table('updates',
    sa.Column('update_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], name='updates_campaign_id_fkey'),
    sa.PrimaryKeyConstraint('update_id', name='updates_pkey')
    )
    # ### end Alembic commands ###
